### ISSUE TITLE
Robot is not the right one

### ISSUE THREAD

**Issue by joao-pm-santos96** [joao-pm-santos96/SmObEx#1]
I'm using the fanuc package but it only includes the m6ib and not my variant (m6ib/6s) which has a shorter arm. What modifications do I have to do in order to correct this? A simple change in the urdf, or a completely new CAD?

In the screenshot the tf should be 0.430 instead of 0.615.

 Thanks! 

@miguelriemoliveira 
-------
Robot measures: http://motioncontrolsrobotics.com/downloads/techdocs/M6_RJ3iB.pdf

![Screenshot from 2019-03-10 13-12-23](https://user-images.githubusercontent.com/47630528/54085444-2932c980-4336-11e9-86b9-63b5b792a5f0.png)

**Comment by joao-pm-santos96** [comment]
Found out a tutorial on how to create the URDF (wiki.ros.org/Industrial/Tutorials/Create%20a%20URDF%20for%20an%20Industrial%20Robot). Now just need the CAD

**Comment by miguelriemoliveira** [comment]
Hi João.  I can help on tuesday morning. You mus changw the urdf and the cad as well

**Comment by miguelriemoliveira** [comment]
and I like your readme, a lot of stuff there already.

**Comment by joao-pm-santos96** [comment]
Yeah sure! Justo to update, I'm able to run ROS on the lrmate 200iD (smaller one), now working on the bigger one
