### ISSUE TITLE
Get the center of the unknown clusters

### ISSUE THREAD

**Issue by joao-pm-santos96** [joao-pm-santos96/SmObEx#14]
Hi! If I have one, two or more clusters of unknown space, how can I tell that they are separate clusters and after that, how do I calculate it's center?

**Comment by miguelriemoliveira** [comment]
Hi

I have done this before ... search octomap tools... i think it is there.

A Qui, 11/04/2019, 18:39, João Santos <notifications@github.com> escreveu:

**Comment by joao-pm-santos96** [comment]
Hello!

Found it in [compare_octrees.cpp](https://github.com/miguelriemoliveira/octomap_tools/blob/master/world_model_consistency_check/src/compare_octrees.cpp). Don't know if it is a direct implementation to the SmObEx case but at least I now know that there is an algorithm for that :smile:

**Comment by joao-pm-santos96** [comment]
Hello!

Since I have a topic publishing a PointCloud2 that contains the center points of the unknown voxels and I have the octomap's resolution, I should be able to use [pcl's Euclidean Cluster Extraction](http://www.pointclouds.org/documentation/tutorials/cluster_extraction.php#cluster-extraction) to fins the centroid of the unknown clusters, right?

**Comment by joao-pm-santos96** [comment]
Done with pcl
