### ISSUE TITLE
Random pose sampling procedure

### ISSUE THREAD

**Issue by joao-pm-santos96** [joao-pm-santos96/SmObEx#16]
Hello @miguelriemoliveira and @rarrais , 

so I was thinking about the best away to generated random valid poses for the camera with tools from MoveIt! and then a question hit me: which is better, to generate random values for the camera position and rotation directly or random joint values? What do you think?

Thnaks!

**Comment by miguelriemoliveira** [comment]
Yes, joint values are an interesting approach but they will not comply with the restriction that you want the camera pointed at the center of the target volume ... perhaps a hybrid, some joints (first three) with joint values, some others (last three) to aim the camera?

**Comment by joao-pm-santos96** [comment]
My implementation so far computes a random (but reachable) pose and the z orientation is obtained bye the position center point and an observation center (for now, the center of the exploration volume). It works, not very good but also not very bad either. Not very good because some poses would collide with the robot pedestal, not very bad because at least all poses have a score above zero. Any suggestion for improvements?

**Comment by miguelriemoliveira** [comment]
Hi @joao-pm-santos96 

lets discuss (very briefly) after Bernardo's presentation this afternoon, and with more detail tomorrow.

**Comment by joao-pm-santos96** [comment]
Ended up generating random reachable poses and them imposing the orientation
