### ISSUE TITLE
Sorting the unknown voxels by distance to camera

### ISSUE THREAD

**Issue by miguelriemoliveira** [joao-pm-santos96/SmObEx#18]
Assume you build a list of class instances, something like this

```cpp

class MyUnknownVoxel
{
   uint32 key;
   center;
   distance_to_camera;

}
```

now with a list of MyUnknownVoxels, you can sort 

```cpp
std::set<MyUnknownVoxel> my_unknown_voxels;
```

using this reference 

https://stackoverflow.com/questions/12823573/c-sorting-class-array

I would imagine you do something like this would work

**Comment by joao-pm-santos96** [comment]
Thanks for the guide, the only change was that it couldn't by a set, but using a vector worked out.

**Comment by miguelriemoliveira** [comment]
Ok, if you really need a vector you could convert the vector back to a set ... not sure you need it though ...
