### ISSUE TITLE
Load calibration parameters outside bringup.launch

### ISSUE THREAD

**Issue by joao-pm-santos96** [joao-pm-santos96/SmObEx#2]
Added a tf_static_publisher to the bringup.launch. Tried to load the extrinsic calibration parameters with <rosparam command=“load” ... /> but wasn’t successful. Ended up putting the parameters directly in the launch file but don’t like that... any recommendation @miguelriemoliveira ?

**Comment by miguelriemoliveira** [comment]
Olá João,

I will send an example attached. I will pass by LAR around 15h to try to help you.

[example.zip](https://github.com/joao-pm-santos96/SmObEx/files/2961942/example.zip)
