### ISSUE TITLE
Calibration not working, always tending to the same wrong solution 

### ISSUE THREAD

**Issue by joao-pm-santos96** [joao-pm-santos96/SmObEx#4]
Hi @miguelriemoliveira, updated the calibration process like we talked two days ago, but when trying to calibrate, the process always tends to the same wrong solution... already compared to @rarrais issue https://github.com/jhu-lcsr/aruco_hand_eye/pull/5 bue didn't changed much... any suggestion? If I hand publish a "calibration" tf of xyz=0 0 0  and rpy=0 0 0 it lays exactly where it should be.
Pictures show the real system and the badly calibrated one. 
Thanks!

![Screenshot from 2019-03-15 09-43-34](https://user-images.githubusercontent.com/47630528/54422998-91ebbe80-4707-11e9-8ec3-2ae0115cd16e.png)

![IMG_0321](https://user-images.githubusercontent.com/47630528/54423025-9f08ad80-4707-11e9-8275-5b2dc660abac.JPG)

**Comment by miguelriemoliveira** [comment]
Hello @joao-pm-santos96 ,

I will try to find some time to go to LAR today. Perhaps at 14h, but I am not sure I will have time. 

If I cannot we talk on Monday ...

**Comment by joao-pm-santos96** [comment]
Thank you! Really appreciate it

**Comment by joao-pm-santos96** [comment]
Found my error, when calling calibration_mode the camera_rgb_optical_frame doenst't match its place... now just have to find where I messed up.

![Screenshot from 2019-03-15 15-57-43](https://user-images.githubusercontent.com/47630528/54444702-3804ec00-473b-11e9-81f0-47c139afef78.png)

**Comment by miguelriemoliveira** [comment]
Why is it solved? Is it working?

**Comment by joao-pm-santos96** [comment]
Yeah seems to be working fine now. Only store_calibration.py not doing what was expected, working on it now

**Comment by joao-pm-santos96** [comment]
Now everything works fine! Thanks for the help, will show it to you next monday!

**Comment by miguelriemoliveira** [comment]
Hi @joao-pm-santos96 , You can close the issue. I just reopened to try to say that, 
whenever you close an issue, you should explain why you close it. For example, this is now working in commit ca39b3eef52d1d1482b26254ab1d89e0430885f5

**Comment by joao-pm-santos96** [comment]
Hello! Ok understood that, will do from now on. Thanks for the help and suggestions!
